package jp.evolvegame.core;

import org.bukkit.*;
import org.bukkit.entity.*;
import org.bukkit.event.*;
import org.bukkit.event.player.*;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.util.RayTraceResult;
import org.bukkit.util.Vector;
import java.util.*;

public final class HunterCombatController implements Listener {
 private final ProjectEvolvePlugin plugin; private final MatchManager match;
 private final NamespacedKey weaponKey, ammoKey; private final Map<UUID,Long> nextShot=new HashMap<>(), reloadUntil=new HashMap<>();
 private final Map<UUID,Tether> tethers=new HashMap<>(); private int tetherTask=-1;
 private record Tether(UUID tracker,UUID monster,long ends,double max){}
 public HunterCombatController(ProjectEvolvePlugin p,MatchManager m){plugin=p;match=m;weaponKey=new NamespacedKey(p,"hunter_weapon");ammoKey=new NamespacedKey(p,"hunter_ammo");tetherTask=Bukkit.getScheduler().scheduleSyncRepeatingTask(p,this::tickTethers,1,1);}
 public void equip(Player p,Role r){clear(p); if(r==Role.ASSAULT){p.getInventory().setItem(0,gun(Material.IRON_HORSE_ARMOR,"ASSAULT RIFLE","rifle",24));p.getInventory().setItem(1,gun(Material.DIAMOND_HORSE_ARMOR,"SHOTGUN","shotgun",6));}else if(r==Role.TRACKER){p.getInventory().setItem(0,gun(Material.IRON_HORSE_ARMOR,"TRACKER CARBINE","carbine",18));p.getInventory().setItem(1,gun(Material.TRIPWIRE_HOOK,"HARPOON WIRE","harpoon",1));}else if(r==Role.MEDIC)p.getInventory().setItem(0,gun(Material.IRON_HORSE_ARMOR,"MEDIC RIFLE","medic_rifle",12));else if(r==Role.SUPPORT)p.getInventory().setItem(0,gun(Material.IRON_HORSE_ARMOR,"SUPPORT RIFLE","support_rifle",16));p.getInventory().setHeldItemSlot(0);p.sendMessage(ChatColor.AQUA+"Hunter: "+ChatColor.WHITE+"Right click = FIRE / F = RELOAD");}
 private ItemStack gun(Material mat,String name,String id,int mag){ItemStack i=new ItemStack(mat);ItemMeta m=i.getItemMeta();m.setDisplayName(ChatColor.AQUA+name);m.getPersistentDataContainer().set(weaponKey,PersistentDataType.STRING,id);m.getPersistentDataContainer().set(ammoKey,PersistentDataType.INTEGER,mag);m.setLore(List.of(ChatColor.GRAY+"Right click: FIRE",ChatColor.GRAY+"F: RELOAD",ChatColor.WHITE+"Ammo: "+mag+" / "+mag));i.setItemMeta(m);return i;}
 public void clear(Player p){for(int s=0;s<9;s++){ItemStack i=p.getInventory().getItem(s);if(id(i)!=null)p.getInventory().setItem(s,null);}tethers.remove(p.getUniqueId());}
 private String id(ItemStack i){return i==null||!i.hasItemMeta()?null:i.getItemMeta().getPersistentDataContainer().get(weaponKey,PersistentDataType.STRING);} private int ammo(ItemStack i){Integer v=i.getItemMeta().getPersistentDataContainer().get(ammoKey,PersistentDataType.INTEGER);return v==null?0:v;}
 private int mag(String id){return switch(id){case"rifle"->24;case"shotgun"->6;case"carbine"->18;case"medic_rifle"->12;case"support_rifle"->16;default->1;};}
 private void ammo(ItemStack i,String id,int n){ItemMeta m=i.getItemMeta();m.getPersistentDataContainer().set(ammoKey,PersistentDataType.INTEGER,n);m.setLore(List.of(ChatColor.GRAY+"Right click: FIRE",ChatColor.GRAY+"F: RELOAD",ChatColor.WHITE+"Ammo: "+n+" / "+mag(id)));i.setItemMeta(m);}
 @EventHandler(ignoreCancelled=true) public void use(PlayerInteractEvent e){if(!e.getAction().isRightClick()||!hunter(e.getPlayer()))return;ItemStack i=e.getItem();String id=id(i);if(id==null)return;e.setCancelled(true);Player p=e.getPlayer();if(reloadUntil.getOrDefault(p.getUniqueId(),0L)>Bukkit.getCurrentTick())return;if(ammo(i)<=0){reload(p,i,id);return;}if(nextShot.getOrDefault(p.getUniqueId(),0L)>Bukkit.getCurrentTick())return;if(id.equals("harpoon"))harpoon(p,i);else fire(p,i,id);}
 @EventHandler(ignoreCancelled=true) public void swap(PlayerSwapHandItemsEvent e){if(!hunter(e.getPlayer()))return;ItemStack i=e.getPlayer().getInventory().getItemInMainHand();String id=id(i);if(id==null)return;e.setCancelled(true);reload(e.getPlayer(),i,id);}
 private void reload(Player p,ItemStack i,String id){if(ammo(i)>=mag(id))return;int t=plugin.getConfig().getInt("hunters.weapons."+id+".reload-ticks",id.equals("shotgun")?36:30);reloadUntil.put(p.getUniqueId(),(long)Bukkit.getCurrentTick()+t);p.sendActionBar(ChatColor.YELLOW+"RELOADING...");Bukkit.getScheduler().runTaskLater(plugin,()->{if(p.isOnline()&&id.equals(id(i))){ammo(i,id,mag(id));p.sendActionBar(ChatColor.GREEN+"RELOADED  "+mag(id)+" / "+mag(id));}},t);}
 private void fire(Player p,ItemStack i,String id){int a=ammo(i)-1;ammo(i,id,a);nextShot.put(p.getUniqueId(),(long)Bukkit.getCurrentTick()+plugin.getConfig().getInt("hunters.weapons."+id+".fire-delay-ticks",id.equals("shotgun")?16:3));if(id.equals("shotgun")){for(int n=0;n<7;n++)ray(p,id,spread(p.getEyeLocation().getDirection(),.12),3.0);}else ray(p,id,p.getEyeLocation().getDirection(),plugin.getConfig().getDouble("hunters.weapons."+id+".damage",4));p.getWorld().playSound(p.getLocation(),Sound.ENTITY_FIREWORK_ROCKET_BLAST,.4f,1.7f);p.sendActionBar(ChatColor.WHITE+id.toUpperCase(Locale.ROOT)+"  "+a+" / "+mag(id));}
 private Vector spread(Vector v,double s){return v.clone().add(new Vector((Math.random()-.5)*s,(Math.random()-.5)*s,(Math.random()-.5)*s)).normalize();}
 private void ray(Player p,String id,Vector d,double dmg){double range=plugin.getConfig().getDouble("hunters.weapons."+id+".range",48);Location eye=p.getEyeLocation();RayTraceResult r=p.getWorld().rayTrace(eye,d,range,FluidCollisionMode.NEVER,true,.35,e->e instanceof LivingEntity&&e!=p);double len=r!=null&&r.getHitPosition()!=null?r.getHitPosition().distance(eye.toVector()):range;line(eye,d,len,Particle.CRIT);if(r!=null&&r.getHitEntity() instanceof Player target&&target.getUniqueId().equals(match.getMonsterId())){MatchManager.DamageResult dr=match.applyMonsterDamage(dmg);p.playSound(p.getLocation(),Sound.ENTITY_ARROW_HIT_PLAYER,.5f,1.8f);p.sendActionBar(ChatColor.RED+"HIT  "+String.format(Locale.US,"%.1f",dr.armorDamage()+dr.healthDamage()));}}
 private void harpoon(Player p,ItemStack i){ammo(i,"harpoon",0);Player m=match.getMonsterId()==null?null:Bukkit.getPlayer(match.getMonsterId());if(m==null)return;RayTraceResult r=p.getWorld().rayTraceEntities(p.getEyeLocation(),p.getEyeLocation().getDirection(),35,.8,e->e==m);if(r!=null&&r.getHitEntity()==m){tethers.put(m.getUniqueId(),new Tether(p.getUniqueId(),m.getUniqueId(),Bukkit.getCurrentTick()+plugin.getConfig().getLong("hunters.harpoon.duration-ticks",120),plugin.getConfig().getDouble("hunters.harpoon.max-length",12)));p.sendActionBar(ChatColor.GOLD+"HARPOON CONNECTED");m.sendActionBar(ChatColor.RED+"HARPOONED");}else p.sendActionBar(ChatColor.GRAY+"HARPOON MISS");}
 private void tickTethers(){Iterator<Tether> it=tethers.values().iterator();while(it.hasNext()){Tether t=it.next();Player h=Bukkit.getPlayer(t.tracker()),m=Bukkit.getPlayer(t.monster());if(h==null||m==null||Bukkit.getCurrentTick()>t.ends()||h.getWorld()!=m.getWorld()){it.remove();continue;}Location a=h.getLocation().add(0,1.1,0),b=m.getLocation().add(0,1.1,0);Vector v=b.toVector().subtract(a.toVector());double l=v.length();if(l>0.1)line(a,v.clone().normalize(),l,Particle.ELECTRIC_SPARK);if(l>t.max())m.setVelocity(m.getVelocity().add(h.getLocation().toVector().subtract(m.getLocation().toVector()).normalize().multiply(.12)));if(l>t.max()*1.5)it.remove();}}
 private void line(Location a,Vector d,double len,Particle particle){for(double x=0;x<len;x+=.75)a.getWorld().spawnParticle(particle,a.clone().add(d.clone().multiply(x)),1,0,0,0,0);}
 private boolean hunter(Player p){Role r=match.getRole(p.getUniqueId());return match.getState()==MatchState.RUNNING&&(r==Role.ASSAULT||r==Role.TRACKER||r==Role.MEDIC||r==Role.SUPPORT);}
 public void shutdown(){if(tetherTask!=-1)Bukkit.getScheduler().cancelTask(tetherTask);tethers.clear();}
}
